Build Faliure if timeout is reached

diff --git a/LumenJenkinsfile.nightly b/LumenJenkinsfile.nightly
--- a/LumenJenkinsfile.nightly
+++ b/LumenJenkinsfile.nightly
@@ -10,117 +10,119 @@ properties([
 def jobStatus = 'FAIL'
 
 node('gideon') {
-    timeout(120){
-
-        writeFile file: 'Vagrantfile', text: '''
-        Vagrant.configure("2") do |config|
-        config.vm.box = "xcode-10.1"
-        
-        config.vm.synced_folder ".", "/vagrant", disabled: true
-        config.vm.define "nightlylumen" do |nightlylumen|
-        nightlylumen.vm.hostname ="nightlylumen"
-
-        nightlylumen.vm.network "public_network", :bridge => "en0: Ethernet 1", auto_config: false
-        nightlylumen.vm.boot_timeout = 900
-        nightlylumen.vm.provider "virtualbox" do |v|
-        v.name = "nightlylumen"
-        v.gui = false
-        v.memory = ENV["NODE_MEMORY"]
-        v.cpus = ENV["NODE_CPU_COUNT"]
-        end
-        nightlylumen.vm.provision "shell", privileged: false, run: "always", inline: <<-SHELL#!/bin/bash -l
-        set -e
-        set -x
-        rm -f agent.jar
-        curl -LO #{ENV['JENKINS_URL']}/jnlpJars/agent.jar
-        nohup java -jar agent.jar -jnlpUrl #{ENV['JENKINS_URL']}/computer/#{ENV['NODE_ID']}/slave-agent.jnlp -secret #{ENV["NODE_SECRET"]} &
-        SHELL
-        end
-        end
-        '''
-
-        vagrant.inside(
-            'Vagrantfile',
-            '/jenkins',
-        2, // CPU
-        8000, // MEMORY
-        12000, // VNC port
-        false, // rebuild image
-        ) { nodeId ->
-            node(nodeId) {
-                try {
-                    stage('Checkout') {
-                        checkout scm
-                    }
-                    stage('Prepare') {
-                        sh '''#!/bin/bash -l
+    try{
+        timeout(120){
+            writeFile file: 'Vagrantfile', text: '''
+            Vagrant.configure("2") do |config|
+                config.vm.box = "xcode-10.1" 
+                config.vm.synced_folder ".", "/vagrant", disabled: true
+                config.vm.define "nightlylumen" do |nightlylumen|
+                    nightlylumen.vm.hostname ="nightlylumen"
+                    nightlylumen.vm.network "public_network", :bridge => "en0: Ethernet 1", auto_config: false
+                    nightlylumen.vm.boot_timeout = 900
+                    nightlylumen.vm.provider "virtualbox" do |v|
+                        v.name = "nightlylumen"
+                        v.gui = false
+                        v.memory = ENV["NODE_MEMORY"]
+                        v.cpus = ENV["NODE_CPU_COUNT"]
+                    end
+                    nightlylumen.vm.provision "shell", privileged: false, run: "always", inline: <<-SHELL#!/bin/bash -l
                         set -e
                         set -x
-                        java -version
-                        node -v
-                        npm -v
-                        brew -v
-                        xcodebuild -version
-                        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
-                        sudo xcodebuild -license accept
-                        fastlane clearCache
-                        fastlane prepare
-                        '''
+                        rm -f agent.jar
+                        curl -LO #{ENV['JENKINS_URL']}/jnlpJars/agent.jar
+                        nohup java -jar agent.jar -jnlpUrl #{ENV['JENKINS_URL']}/computer/#{ENV['NODE_ID']}/slave-agent.jnlp -secret #{ENV["NODE_SECRET"]} &
+                    SHELL
+                end
+            end
+            '''
+
+            vagrant.inside(
+                'Vagrantfile',
+                '/jenkins',
+            2, // CPU
+            8000, // MEMORY
+            12000, // VNC port
+            false, // rebuild image
+            ) { nodeId ->
+                node(nodeId) {
+                    try {
+                        stage('Checkout') {
+                            checkout scm
+                        }
+                        stage('Prepare') {
+                            sh '''#!/bin/bash -l
+                            set -e
+                            set -x
+                            java -version
+                            node -v
+                            npm -v
+                            brew -v
+                            xcodebuild -version
+                            pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
+                            sudo xcodebuild -license accept
+                            fastlane clearCache
+                            fastlane prepare
+                            '''
+                        }
+                        stage('Build & Upload') {
+                            withCredentials([
+                                [
+                                $class          : 'UsernamePasswordMultiBinding',
+                                credentialsId   : '85859bba-4927-4b14-bfdf-aca726009962',
+                                passwordVariable: 'GITHUB_PASSWORD',
+                                usernameVariable: 'GITHUB_USERNAME',
+                                ],
+                                string(credentialsId: '8b4f7459-c446-4058-be61-3c3d98fe72e2', variable: 'ITUNES_USER'),
+                                string(credentialsId: '05be12cd-5177-4adf-9812-809f01451fa0', variable: 'FASTLANE_PASSWORD'),
+                                string(credentialsId: 'ab91f92a-4588-4034-8d7f-c1a741fa31ab', variable: 'FASTLANE_ITC_TEAM_ID'),
+                                string(credentialsId: 'ee93743c-b0be-46aa-b49a-ab3caaea4f67', variable: 'MATCH_PASSWORD'),
+                                string(credentialsId: 'c454a3e9-83af-480a-82fe-08c858512140', variable: 'SentryDSN'),
+                                string(credentialsId: 'f206e880-e09a-4369-a3f6-f86ee94481f2', variable: 'SENTRY_AUTH_TOKEN'),
+                                string(credentialsId: 'cc9215e4-ca8f-41bd-9e0b-1c2ba1900949', variable: 'LumenAPIKey'),
+                                string(credentialsId: 'b4293427-ece9-48c5-8069-caf7fe7d5f3b', variable: 'RevenuecatAPIKey')])
+                            {
+                                sh '''#!/bin/bash -l
+                                set -x
+                                set -e
+                                rm -rf /Users/vagrant/Library/Keychains/ios-build.keychain*
+                                export MATCH_KEYCHAIN_NAME=ios-build.keychain
+                                rm -rf ../build-tools
+                                export app_name=Lumen
+                                export CommitHash=`git rev-parse --short HEAD`
+                                echo de > shipping_locales.txt && echo en-US >> shipping_locales.txt
+                                fastlane importLocalizations
+                                fastlane lumenBeta
+                                '''
+                            }
+                        }
+                        jobStatus = 'PASS'
                     }
-                    stage('Build & Upload') {
-                        withCredentials([
-                            [
-                            $class          : 'UsernamePasswordMultiBinding',
-                            credentialsId   : '85859bba-4927-4b14-bfdf-aca726009962',
-                            passwordVariable: 'GITHUB_PASSWORD',
-                            usernameVariable: 'GITHUB_USERNAME',
-                            ],
-                            string(credentialsId: '8b4f7459-c446-4058-be61-3c3d98fe72e2', variable: 'ITUNES_USER'),
-                            string(credentialsId: '05be12cd-5177-4adf-9812-809f01451fa0', variable: 'FASTLANE_PASSWORD'),
-                            string(credentialsId: 'ab91f92a-4588-4034-8d7f-c1a741fa31ab', variable: 'FASTLANE_ITC_TEAM_ID'),
-                            string(credentialsId: 'ee93743c-b0be-46aa-b49a-ab3caaea4f67', variable: 'MATCH_PASSWORD'),
-                            string(credentialsId: 'c454a3e9-83af-480a-82fe-08c858512140', variable: 'SentryDSN'),
-                            string(credentialsId: 'f206e880-e09a-4369-a3f6-f86ee94481f2', variable: 'SENTRY_AUTH_TOKEN'),
-                            string(credentialsId: 'cc9215e4-ca8f-41bd-9e0b-1c2ba1900949', variable: 'LumenAPIKey'),
-                            string(credentialsId: 'b4293427-ece9-48c5-8069-caf7fe7d5f3b', variable: 'RevenuecatAPIKey')])
-                        {
+                    catch(all) {
+                        jobStatus = 'FAIL'
+                        print "Something Failed. Check the above logs."
+                        emailext(
+                            to: 'iosdev@cliqz.com',
+                            subject: '$PROJECT_NAME - Build # $BUILD_NUMBER Failed!!!',
+                            body: '\n\nCheck console output at ' + env.BUILD_URL + ' to view the cause.'
+                        )
+                        currentBuild.result = 'FAILURE'
+                    }
+                    finally {
+                        stage("Clean Up"){
                             sh '''#!/bin/bash -l
                             set -x
                             set -e
-                            rm -rf /Users/vagrant/Library/Keychains/ios-build.keychain*
-                            export MATCH_KEYCHAIN_NAME=ios-build.keychain
-                            rm -rf ../build-tools
-                            export app_name=Lumen
-                            export CommitHash=`git rev-parse --short HEAD`
-                            echo de > shipping_locales.txt && echo en-US >> shipping_locales.txt
-                            fastlane importLocalizations
-                            fastlane lumenBeta
+                            fastlane clearCache
                             '''
                         }
-                    }
-                    jobStatus = 'PASS'
-                }
-                catch(all) {
-                    jobStatus = 'FAIL'
-                    print "Something Failed. Check the above logs."
-                    emailext(
-                        to: 'iosdev@cliqz.com',
-                        subject: '$PROJECT_NAME - Build # $BUILD_NUMBER Failed!!!',
-                        body: '\n\nCheck console output at ' + env.BUILD_URL + ' to view the cause.'
-                    )
-                    currentBuild.result = 'FAILURE'
-                }
-                finally {
-                    stage("Clean Up"){
-                        sh '''#!/bin/bash -l
-                        set -x
-                        set -e
-                        fastlane clearCache
-                        '''
                     }
                 }
             }
         }
+    } catch(err){
+        echo 'Build was not completed before timeout'
+        currentBuild.result = 'FAILURE'
     }
 }
 if (jobStatus == 'PASS') {
